services:
  - type: web
    name: flavorshare-backend
    env: node
    plan: free
    repo: https://github.com/patmbugus/MERN-final-project
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false